node testAverage.js
node testEven.js
node testFiboReverse.js
node testGreatest.js
node testLowest.js
node testMappLengths.js
node testOdd.js
node testReverseNumbers.js
node testSecondElement.js
node testSumOfNum.js
node testCountOdd.js
